### ISSUE TITLE
Module import addressing

### ISSUE THREAD

**Issue by xxBXSD** [amnuts/rotary-controlled-oled-menu#1]
Hi, in the SSD1306.py script, you have the line 108 is 'import I2C', this doesn't work because those modules are in the 'Adafruit' directory. The code needs to read 'import Adafruit.I2C as I2C'. Same goes for line 80 in 'I2C.py', the code needs to read 'import Adafruit.PureIO as PureIO'. I assume that the modules were moved after it was tested! :-)

**Comment by amnuts** [comment]
Wow, I super suck at noticing issues on repos!!

Two years ago you posted this and I didn't notice.  Four months ago I updated the code, and _still_ didn't notice! 🤦 

I did fix this in the end, and I really do appreciate your feedback... even though I didn't see or respond to it in a timely fashion! 😊
